# 创建 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobless-service
  namespace: flow
  labels:
    app: jobless-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobless-service
  template:
    metadata:
      labels:
        app: jobless-service
    spec:
      serviceAccountName: flow
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: aliyun-docker-secret
      containers:
        - name: jobless-service
          image: ${SERVICE_IMAGE}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 1
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: config
              mountPath: /application.yaml
              subPath: application.yaml
      initContainers:
        - name: init-zeebe-gateway
          image: busybox
          imagePullPolicy: IfNotPresent
          command: [ 'sh', '-c', "until nc -z zeebe-zeebe-gateway.zeebe 26500; do echo waiting for zeebe-gateway; sleep 2; done" ]
      volumes:
        - name: config
          configMap:
            name: jobless-service-config
            items:
              - key: application.yaml
                path: application.yaml