# 创建 Ingress
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jobless-service
  namespace: flow
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: jobless-service
              servicePort: 80
      host: jobless.flow.wgv.ink