# 添加服务账号
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flow
  namespace: flow
automountServiceAccountToken: true
---
# 添加角色
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flow-reader
  namespace: flow
rules:
  - apiGroups: [ "", "extensions", "apps" ]
    resources: [ "functions" ]
    verbs: [ "get", "list", "watch" ]
---
# 添加角色绑定
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flow-reader-binding
  namespace: flow
subjects:
  - kind: ServiceAccount
    name: flow
    namespace: flow
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: flow-reader
  apiGroup: ""