replicaCount: 1

image:
  repository: dustlightcn/jobless-service
  tag: "latest"

ingress:
  className: "nginx"
  host: "jobless.dustlight.cn"

zeebe:
  host: zeebe-zeebe-gateway.zeebe
  port: 26500

type: function

logging: debug