# 创建 jobless-service 配置文件
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-service-config
data:
  application.yaml: |-
    dustlight:
      jobless:
        kubeless:
          type: {{ .Values.type }}
        zeebe:
          gateway: {{ .Values.zeebe.host }}:{{ .Values.zeebe.port }}
    management:
      endpoint:
        health:
          show-details: always
          group:
            readness:
              include: ping
            liveness:
              include:
                - managerChecker
                - providerChecker
    logging:
      level:
        cn.dustlight.jobless.*: {{ .Values.logging }}