# 添加服务账号
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
automountServiceAccountToken: true
---
# 添加角色
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-reader
rules:
  - apiGroups: [ "", "kubeless.io" ]
    resources: [ "functions" , "httptriggers" ]
    verbs: [ "get", "list", "watch" ]
---
# 添加角色绑定
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-reader-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-reader
  apiGroup: ""