# 创建服务
apiVersion: v1
kind: Service
metadata:
  name: jobless-service
  namespace: flow
  labels:
    app: jobless-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: jobless-service
  type: ClusterIP